In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#scalar

scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector

vector = torch.tensor([7, 7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix

MATRIX = torch.tensor([[7, 2], [2,3], [3, 2]])

In [ ]:
MATRIX

tensor([[7, 2],
        [2, 3],
        [3, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([2, 3])

In [ ]:
MATRIX.shape

torch.Size([3, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[2, 3, 4], [1, 2, 3], [4, 5, 6]]])

In [ ]:
TENSOR

tensor([[[2, 3, 4],
         [1, 2, 3],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR1 = torch.tensor([[[[2], [2], [3]]]])

In [ ]:
TENSOR1.ndim

4

In [ ]:
TENSOR1.shape

torch.Size([1, 1, 3, 1])

In [ ]:
#Random tensors

random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

tensor([[0.9055, 0.6423, 0.5432, 0.8469],
        [0.0748, 0.2957, 0.5270, 0.4526],
        [0.0640, 0.7849, 0.7076, 0.4917]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channels(r, g, b)

In [ ]:
random_image_size_tensor

tensor([[[0.9788, 0.1883, 0.9871],
         [0.1498, 0.1726, 0.4854],
         [0.1459, 0.8923, 0.1693],
         ...,
         [0.0879, 0.7753, 0.2065],
         [0.8577, 0.1824, 0.0759],
         [0.1335, 0.9170, 0.4170]],

        [[0.1939, 0.5382, 0.3706],
         [0.2106, 0.1525, 0.0435],
         [0.5495, 0.6223, 0.9751],
         ...,
         [0.7172, 0.7950, 0.7906],
         [0.2062, 0.1957, 0.6563],
         [0.0482, 0.0223, 0.4933]],

        [[0.2939, 0.3712, 0.2338],
         [0.2339, 0.5021, 0.6544],
         [0.4092, 0.4027, 0.4901],
         ...,
         [0.4522, 0.6698, 0.5196],
         [0.4974, 0.1205, 0.0442],
         [0.4313, 0.6628, 0.5165]],

        ...,

        [[0.1499, 0.4144, 0.4131],
         [0.8797, 0.2756, 0.4776],
         [0.6236, 0.4010, 0.4101],
         ...,
         [0.3981, 0.5134, 0.8542],
         [0.6775, 0.7712, 0.5250],
         [0.1767, 0.3258, 0.5894]],

        [[0.5473, 0.8855, 0.8498],
         [0.8521, 0.0949, 0.9203],
         [0.

In [ ]:
zeros = torch.zeros(3, 2)

In [ ]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
ones = torch.ones(1, 5)

In [ ]:
ones

tensor([[1., 1., 1., 1., 1.]])

In [ ]:
to_ten = torch.arange(1, 10)

In [ ]:
ten_zeros = torch.zeros_like(to_ten) #Similiar shape

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Manipulating Tensors
tensor = torch.tensor([1,2,3])

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor *22

tensor([22, 44, 66])

In [ ]:
tensor-1

tensor([0, 1, 2])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
  # Matrix multiplication
tensor * tensor


tensor([1, 4, 9])

In [ ]:
tensor * torch.tensor([22, 143, 22])

tensor([ 22, 286,  66])

In [ ]:
torch.tensor([[1,2,3], [4, 5, 6]]) * torch.tensor([[3, 2, 11], [3, 6, 5]])

tensor([[ 3,  4, 33],
        [12, 30, 30]])

In [ ]:
# tensor.matmul() - very fast matrix mult method

In [ ]:
# Transpose

random_tensor.t()

tensor([[0.9055, 0.0748, 0.0640],
        [0.6423, 0.2957, 0.7849],
        [0.5432, 0.5270, 0.7076],
        [0.8469, 0.4526, 0.4917]])

In [ ]:
#

torch.max(random_tensor)

tensor(0.9055)

In [ ]:
torch.min(random_tensor)

tensor(0.0640)

In [ ]:
torch.mean(random_tensor)

tensor(0.5280)

In [ ]:
torch.sum(random_tensor)

tensor(6.3363)

In [ ]:
random_tensor.argmin()

tensor(8)

In [ ]:
random_tensor.argmax()

tensor(0)

In [ ]:
# x.reshape() x.view() torch.stack()

In [ ]:
# torch.squeeze() - remove all single dimensions
# torch.unsqueeze() - adds a single dimension to a targer tensor at a specific dimension

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# torch.tensor([1,2,3], device='cuda')