In [1]:
import torch

In [22]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [23]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32,
                        device = device, requires_grad = True)

In [24]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [25]:
my_tensor.shape

torch.Size([2, 3])

In [26]:
type(my_tensor)

torch.Tensor

In [27]:
my_tensor.dtype

torch.float32

In [28]:
my_tensor.device

device(type='cpu')

In [29]:
# Other common initialization methods

In [32]:
# not initialized data(very small numbers -> close to the zero)
x = torch.empty(size = (3, 3))

In [33]:
x = torch.zeros(size = (3, 3))

In [34]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.rand((3, 3))

tensor([[0.9247, 0.2614, 0.5563],
        [0.8660, 0.7849, 0.0053],
        [0.7251, 0.4490, 0.4839]])

In [36]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
torch.arange(start = 0, end = 5, step=1)

tensor([0, 1, 2, 3, 4])

In [41]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [45]:
x = torch.diag(torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

In [46]:
x

tensor([1, 5, 9])

In [54]:
# torch data types

In [55]:
x.bool()

tensor([True, True, True])

In [56]:
x.float() #float32

tensor([1., 5., 9.])

In [57]:
x.short() #int16

tensor([1, 5, 9], dtype=torch.int16)

In [58]:
x.long() #int64

tensor([1, 5, 9])

In [53]:
x.half() #float16

tensor([1., 5., 9.], dtype=torch.float16)

In [59]:
x.double() #float64

tensor([1., 5., 9.], dtype=torch.float64)

In [60]:
# numpy and pytorch

In [61]:
import numpy as np

In [62]:
np_array = np.ndarray([1, 2, 3])

In [63]:
np_array

array([[[1.82706909e-316, 0.00000000e+000, 2.35541533e-312],
        [7.35613463e+223, 3.03667987e-152, 9.54595513e-307]]])

In [64]:
torch.from_numpy(np_array)

tensor([[[1.8271e-316,  0.0000e+00, 2.3554e-312],
         [7.3561e+223, 3.0367e-152, 9.5460e-307]]], dtype=torch.float64)

In [65]:
x

tensor([1, 5, 9])

In [67]:
x.numpy()

array([1, 5, 9])

In [68]:
# meth operations

In [69]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [70]:
x+y

tensor([5, 7, 9])

In [71]:
x-y

tensor([-3, -3, -3])

In [72]:
x/y

tensor([0.2500, 0.4000, 0.5000])

In [73]:
torch.true_divide(x, y)

tensor([0.2500, 0.4000, 0.5000])

In [74]:
# operation_ means that this operation does inplace

In [75]:
x.pow(2)

tensor([1, 4, 9])

In [76]:
x ** 2

tensor([1, 4, 9])

In [77]:
x1 = torch.rand((2, 5))

In [78]:
x2 = torch.rand((5, 3))

In [79]:
x1, x2

(tensor([[0.8677, 0.3458, 0.3100, 0.7667, 0.1883],
         [0.9395, 0.2780, 0.3981, 0.4825, 0.4288]]),
 tensor([[0.0845, 0.5360, 0.5579],
         [0.9154, 0.7009, 0.5249],
         [0.2488, 0.0706, 0.5327],
         [0.4390, 0.9522, 0.1285],
         [0.4821, 0.8623, 0.5829]]))

In [80]:
torch.mm(x1, x2)

tensor([[0.8944, 1.6218, 1.0391],
        [0.8515, 1.5557, 1.1942]])

In [81]:
x1 @ x2

tensor([[0.8944, 1.6218, 1.0391],
        [0.8515, 1.5557, 1.1942]])

In [82]:
x1.mm(x2)

tensor([[0.8944, 1.6218, 1.0391],
        [0.8515, 1.5557, 1.1942]])

In [83]:
x1**2

tensor([[0.7530, 0.1196, 0.0961, 0.5879, 0.0355],
        [0.8827, 0.0773, 0.1585, 0.2328, 0.1839]])

In [84]:
x1.matrix_power(2)

RuntimeError: linalg.matrix_power: A must be batches of square matrices, but they are 2 by 5 matrices

In [85]:
x, y

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [86]:
torch.dot(x, y)

tensor(32)

In [87]:
x.dot(y)

tensor(32)

In [88]:
# broadcasting

In [89]:
x - y

tensor([-3, -3, -3])

In [90]:
x1 = torch.rand((2, 2))
x2 = torch.rand((2, 2))

In [91]:
x1, x2

(tensor([[0.1577, 0.8677],
         [0.0672, 0.0479]]),
 tensor([[0.2059, 0.1016],
         [0.7112, 0.3595]]))

In [92]:
x1 - x2

tensor([[-0.0482,  0.7661],
        [-0.6441, -0.3116]])

x1 ** x2

In [97]:
x1.sum(dim = 0) # columns

tensor([0.2249, 0.9156])

In [98]:
x1.sum(dim = 1) #rows

tensor([1.0254, 0.1151])

In [101]:
torch.min(x1, dim = 1).values

tensor([0.1577, 0.0479])

In [104]:
torch.argmin(x1)

tensor(3)

In [105]:
torch.eq(x1, x2)

tensor([[False, False],
        [False, False]])

In [109]:
x1.sort(dim = 0, descending = True)

torch.return_types.sort(
values=tensor([[0.1577, 0.8677],
        [0.0672, 0.0479]]),
indices=tensor([[0, 0],
        [1, 1]]))

In [112]:
# all element are below or higher than .. will be 0
torch.clamp(x1, max = 0) 

tensor([[0., 0.],
        [0., 0.]])

In [114]:
torch.all(x1)

tensor(True)

In [115]:
x = torch.tensor([1, 1, 1, 0, 1])

In [116]:
torch.any(x)

tensor(True)

In [117]:
torch.all(x) # because there is one zero in the tensor

tensor(False)

In [118]:
# indexing

In [125]:
x = torch.rand((10, 10))

In [126]:
x

tensor([[0.8716, 0.3818, 0.0693, 0.4000, 0.9646, 0.6669, 0.9750, 0.2923, 0.3289,
         0.9049],
        [0.3843, 0.4442, 0.7595, 0.6799, 0.5860, 0.2648, 0.9418, 0.9669, 0.8835,
         0.8552],
        [0.0088, 0.9083, 0.5023, 0.8742, 0.6718, 0.3603, 0.0626, 0.0362, 0.1582,
         0.3201],
        [0.8861, 0.2260, 0.3524, 0.5885, 0.3281, 0.9193, 0.2925, 0.1358, 0.3787,
         0.9722],
        [0.1786, 0.2574, 0.9288, 0.3532, 0.2159, 0.3915, 0.9375, 0.5916, 0.3553,
         0.1229],
        [0.8156, 0.7349, 0.1502, 0.3582, 0.9775, 0.6517, 0.5345, 0.5923, 0.0495,
         0.9464],
        [0.6272, 0.3666, 0.6531, 0.6000, 0.1093, 0.2934, 0.9806, 0.9790, 0.3464,
         0.0443],
        [0.2728, 0.8177, 0.6946, 0.4432, 0.1740, 0.2611, 0.9920, 0.8553, 0.7808,
         0.1474],
        [0.0229, 0.0442, 0.4808, 0.8169, 0.0908, 0.9123, 0.1784, 0.9865, 0.9555,
         0.3293],
        [0.0174, 0.9671, 0.3234, 0.5604, 0.9631, 0.4699, 0.4624, 0.0853, 0.5811,
         0.0039]])

In [127]:
x[0]

tensor([0.8716, 0.3818, 0.0693, 0.4000, 0.9646, 0.6669, 0.9750, 0.2923, 0.3289,
        0.9049])

In [128]:
x[:, 0]

tensor([0.8716, 0.3843, 0.0088, 0.8861, 0.1786, 0.8156, 0.6272, 0.2728, 0.0229,
        0.0174])

In [129]:
x[2, 0:6]

tensor([0.0088, 0.9083, 0.5023, 0.8742, 0.6718, 0.3603])

In [130]:
x[[2, 5, 8]]

tensor([[0.0088, 0.9083, 0.5023, 0.8742, 0.6718, 0.3603, 0.0626, 0.0362, 0.1582,
         0.3201],
        [0.8156, 0.7349, 0.1502, 0.3582, 0.9775, 0.6517, 0.5345, 0.5923, 0.0495,
         0.9464],
        [0.0229, 0.0442, 0.4808, 0.8169, 0.0908, 0.9123, 0.1784, 0.9865, 0.9555,
         0.3293]])

In [131]:
# useful operations

In [135]:
x = torch.tensor([0.1, 0.2, 1, 2])

In [136]:
torch.where(x > 0.5, x, x**2)

tensor([0.0100, 0.0400, 1.0000, 2.0000])

In [137]:
# tensor reshaping

In [138]:
x = torch.rand((3, 3))

In [139]:
x

tensor([[0.1890, 0.8019, 0.2591],
        [0.2749, 0.0550, 0.5809],
        [0.9683, 0.6486, 0.6994]])

In [146]:
x.view(-1, 9)

tensor([[0.1890, 0.8019, 0.2591, 0.2749, 0.0550, 0.5809, 0.9683, 0.6486, 0.6994]])

In [147]:
x.t()

tensor([[0.1890, 0.2749, 0.9683],
        [0.8019, 0.0550, 0.6486],
        [0.2591, 0.5809, 0.6994]])

In [ ]:
x.permut